### PR TITLE
Fix artist.sh

### PR DESCRIPTION
**Pull request by NotFounds**
Thanks for providing a nice plugin!
There was a bug where artist information was not displayed, so it's fixed.

I am sorry that my English is so bad.

### CODE REVIEW

**Review by Ephigenia — APPROVED** [review]
just tested this and current_track_proprty is correct for spotify!

**Review by pljanicki — APPROVED** [review]
I can confirm that the fix works

**Comment by michelegera** [comment]
Can confirm it works for me too, thanks @NotFounds 

@robhurring can we please get this merged? 🙏

**Comment by robhurring** [comment]
Sorry for the late reply here - thanks for the fix @NotFounds!

**Pull request merged**
